name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: npm install
        run: npm install

      - name: Install Expo CLI
        run: npm install --global expo-cli

      - name: Login to EAS
        run: expo login --username ${{ secrets.EAS_USERNAME }} --password ${{ secrets.EAS_PASSWORD }}

      - name: Build APK
        run: npx eas build --platform android
