name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Clear NPM cache
        run: npm cache clean --force

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Install Expo CLI
        run: yarn global add expo-cli
        env:
          EXPO_CLI_YES: 1

      - name: Login to EAS
        run: npx eas login --username ${{ secrets.EAS_USERNAME }} --password ${{ secrets.EAS_PASSWORD }}

      - name: Build APK
        run: npx eas build --platform android
